parameters:
  removeDeployment: true
  prerelease: false
  templateFilePath: ''
  moduleResourceGroupName: ''

stages:
  - stage: A
    jobs:
      - job: JA
        steps:
          - script: |
              echo "This is job Foo."
              echo "##vso[task.setvariable variable=doThing;isOutput=true]Yes" #The variable doThing is set to 'Yes'
            name: DetermineResult

  #stage B runs if DetermineResult task set doThing variable on stage A
  - stage: B
    dependsOn: A
    condition: eq(dependencies.A.outputs['JA.DetermineResult.doThing'], 'Yes')
    jobs:
      - job: JB
        steps:
          - bash: echo "Hello world stage B first job"
