name: Docs/Wiki Sync

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    # paths:
    #   - "docs/wiki/**"

env:
  wiki_source_repo: "${{ github.repository }}"
  wiki_source_repo_dir: "${{ github.repository }}/docs/wiki"
  wiki_target_repo: "${{ github.repository }}.wiki"
  github_commit_message: "Wiki Sync from docs/wiki"
  pipelinePrincipalGitUserName: "CARMLPipelinePrincipal"
  pipelinePrincipalGitUserEmail: "CARML@microsoft.com"

jobs:
  sync-wiki:
    name: Sync docs/wiki to Wiki
    # if: github.repository == '${{ github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.wiki_source_repo }}
          path: ${{ env.wiki_source_repo }}
          token: '${{ secrets.PLATFORM_REPO_UPDATE_PAT }}' # Sets general GIT credentials up

      - name: Checkout Wiki Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.wiki_target_repo }}
          path: ${{ env.wiki_target_repo }}
          token: '${{ secrets.PLATFORM_REPO_UPDATE_PAT }}' # Sets general GIT credentials up

      # - name: "Checkout"
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      #     token: '${{ secrets.PLATFORM_REPO_UPDATE_PAT }}' # Sets general GIT credentials up
      # - name: Set environment variables
        # uses: deep-mm/set-variables@v1.0
        # with:
        #   # Name of variable file
        #   variableFileName: 'variables.module' # Don't write .json here
      # - name: Checkout Wiki Repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ env.wiki_target_repo }}
      #     path: ${{ env.wiki_target_repo }}
      #     token: '${{ secrets.PLATFORM_REPO_UPDATE_PAT }}' # Sets general GIT credentials up
      # - name: Sync wiki
      #   shell: pwsh
      #   run: |
      #     git config --global user.name '${{ env.pipelinePrincipalGitUserName }}'
      #     git config --global user.email '${{ env.pipelinePrincipalGitUserEmail }}'

      #     Write-Verbose "wiki_source_repo_dir: [${{ env.wiki_source_repo_dir }}]" -Verbose
      #     Write-Verbose "wiki_target_repo: [${{ env.wiki_target_repo }}]" -Verbose

      #     rsync -avzr --delete --exclude='.git/' "${{ env.wiki_source_repo_dir }}/" "${{ env.wiki_target_repo }}]"

      #     git pull
      #     git add .
      #     git commit -m ""$github_commit_message [$GITHUB_ACTOR/${GITHUB_SHA::8}]"
      #     git push

      #     # git add .
      #     # git commit -m "
      #     # git push --set-upstream https://$GITHUB_TOKEN@github.com/$wiki_target_repo.git main
      #   working-directory: ${{ env.GITHUB_WORKSPACE }}


      - name: Configure Local Git
        run: |
          git config --global user.name '${{ env.pipelinePrincipalGitUserName }}'
          git config --global user.email '${{ env.pipelinePrincipalGitUserEmail }}'
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Sync docs/wiki Into Wiki Repo
        shell: pwsh
        run: |
          Write-Verbose "wiki_source_repo_dir: [${{ env.wiki_source_repo_dir }}]" -Verbose
          Write-Verbose "wiki_target_repo: [${{ env.wiki_target_repo }}]" -Verbose

          rsync -avzr --delete --exclude='.git/' "${{ env.wiki_source_repo_dir }}/" "${{ env.wiki_target_repo }}"
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Stage & Push Files Into Wiki Repo
        run: |
          # git add .
          # git commit -m "$github_commit_message [$GITHUB_ACTOR/${GITHUB_SHA::8}]"
          # git push

          Get-Location
          git branch

          git add .
          git commit -m "$github_commit_message [$GITHUB_ACTOR/${GITHUB_SHA::8}]"
          git push --set-upstream https://${{secrets.PLATFORM_REPO_UPDATE_PAT}}@github.com/$wiki_target_repo.git main
        working-directory: ${{ env.wiki_target_repo }}
